name: "call"

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "发布版本"
        required: true
        default: "v1.0.0"


jobs:
  output:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: "output version"
        run: |
          echo "hello world"
