on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "发布版本"
        default: "v1.0.0"
jobs:
  output:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: "output version"
        run: |
          ls
          echo ${input.version}
