name: "ci"

on:
  push:
    branches:
      - main
jobs:
  output:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: echo hello world
        run: |
          echo "hello world"

      - name: "call action"
        uses: ./.github/actions/call.yaml
        with:
          version: "v1.0.1"