name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Sub-Workflow
        uses: user-zouyu/test/.github/workflows/sub-workflow.yml@{main}
        with:
          my_param: my_value